// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=parse -id save -d VecType=saveVec -d Type=save github.com/platinasystems/elib/vec.tmpl]

package parse

import (
	"github.com/platinasystems/elib"
)

type saveVec []save

func (p *saveVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]save, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *saveVec) validate(i uint, zero *save) *save {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]save, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *saveVec) Validate(i uint) *save                { return p.validate(i, (*save)(nil)) }
func (p *saveVec) ValidateInit(i uint, zero save) *save { return p.validate(i, &zero) }

func (p saveVec) Len() uint { return uint(len(p)) }
