// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id freeElt -d VecType=freeEltVec -d Type=freeElt vec.tmpl]

package elib

type freeEltVec []freeElt

func (p *freeEltVec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]freeElt, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *freeEltVec) validate(i uint, zero *freeElt) *freeElt {
	c := Index(cap(*p))
	l := Index(i) + 1
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]freeElt, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *freeEltVec) Validate(i uint) *freeElt                   { return p.validate(i, (*freeElt)(nil)) }
func (p *freeEltVec) ValidateInit(i uint, zero freeElt) *freeElt { return p.validate(i, &zero) }

func (p freeEltVec) Len() uint { return uint(len(p)) }
