// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id freeElts -d VecType=freeEltsVec -d Type=freeEltVec vec.tmpl]

package elib

type freeEltsVec []freeEltVec

func (p *freeEltsVec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]freeEltVec, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *freeEltsVec) Validate(i uint) *freeEltVec {
	c := Index(cap(*p))
	l := Index(i) + 1
	if l > c {
		c = NextResizeCap(l)
		q := make([]freeEltVec, l, c)
		copy(q, *p)
		*p = q
	}
	if l > Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}

func (p freeEltsVec) Len() uint { return uint(len(p)) }
