// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id freeElts -d VecType=freeEltsVec -d Type=freeEltVec vec.tmpl]

package elib

type freeEltsVec []freeEltVec

func (p *freeEltsVec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]freeEltVec, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *freeEltsVec) validate(i uint, zero *freeEltVec) *freeEltVec {
	c := Index(cap(*p))
	l := Index(i) + 1
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]freeEltVec, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *freeEltsVec) Validate(i uint) *freeEltVec                      { return p.validate(i, (*freeEltVec)(nil)) }
func (p *freeEltsVec) ValidateInit(i uint, zero freeEltVec) *freeEltVec { return p.validate(i, &zero) }

func (p freeEltsVec) Len() uint { return uint(len(p)) }
