// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Bitmap -d VecType=BitmapVec -d Type=Bitmap vec.tmpl]

package elib

type BitmapVec []Bitmap

func (p *BitmapVec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]Bitmap, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *BitmapVec) validate(i uint, zero *Bitmap) *Bitmap {
	c := Index(cap(*p))
	l := Index(i) + 1
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]Bitmap, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *BitmapVec) Validate(i uint) *Bitmap                  { return p.validate(i, (*Bitmap)(nil)) }
func (p *BitmapVec) ValidateInit(i uint, zero Bitmap) *Bitmap { return p.validate(i, &zero) }

func (p BitmapVec) Len() uint { return uint(len(p)) }
