// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Int64 -d VecType=Int64Vec -d Type=int64 vec.tmpl]

package elib

type Int64Vec []int64

func (p *Int64Vec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]int64, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *Int64Vec) validate(i uint, zero *int64) *int64 {
	c := Index(cap(*p))
	l := Index(i) + 1
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]int64, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *Int64Vec) Validate(i uint) *int64                 { return p.validate(i, (*int64)(nil)) }
func (p *Int64Vec) ValidateInit(i uint, zero int64) *int64 { return p.validate(i, &zero) }

func (p Int64Vec) Len() uint { return uint(len(p)) }
