// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Uint64 -d VecType=Uint64Vec -d Type=uint64 vec.tmpl]

package elib

type Uint64Vec []uint64

func (p *Uint64Vec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]uint64, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *Uint64Vec) validate(i uint, zero *uint64) *uint64 {
	c := Index(cap(*p))
	l := Index(i) + 1
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]uint64, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *Uint64Vec) Validate(i uint) *uint64                  { return p.validate(i, (*uint64)(nil)) }
func (p *Uint64Vec) ValidateInit(i uint, zero uint64) *uint64 { return p.validate(i, &zero) }

func (p Uint64Vec) Len() uint { return uint(len(p)) }
