// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Word -d VecType=WordVec -d Type=Word vec.tmpl]

package elib

type WordVec []Word

func (p *WordVec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]Word, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *WordVec) validate(i uint, zero *Word) *Word {
	c := Index(cap(*p))
	l := Index(i) + 1
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]Word, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *WordVec) Validate(i uint) *Word                { return p.validate(i, (*Word)(nil)) }
func (p *WordVec) ValidateInit(i uint, zero Word) *Word { return p.validate(i, &zero) }

func (p WordVec) Len() uint { return uint(len(p)) }
