// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=mctree -id dump_node -d VecType=dump_node_vec -d Type=dump_node github.com/platinasystems/elib/vec.tmpl]

package mctree

import (
	"github.com/platinasystems/elib"
)

type dump_node_vec []dump_node

func (p *dump_node_vec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]dump_node, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *dump_node_vec) validate(i uint, zero *dump_node) *dump_node {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]dump_node, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *dump_node_vec) Validate(i uint) *dump_node                     { return p.validate(i, (*dump_node)(nil)) }
func (p *dump_node_vec) ValidateInit(i uint, zero dump_node) *dump_node { return p.validate(i, &zero) }

func (p dump_node_vec) Len() uint { return uint(len(p)) }
