// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=mctree -id Pair -d VecType=pair_vec -d Type=Pair github.com/platinasystems/elib/vec.tmpl]

package mctree

import (
	"github.com/platinasystems/elib"
)

type pair_vec []Pair

func (p *pair_vec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Pair, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *pair_vec) validate(i uint, zero *Pair) *Pair {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]Pair, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *pair_vec) Validate(i uint) *Pair                { return p.validate(i, (*Pair)(nil)) }
func (p *pair_vec) ValidateInit(i uint, zero Pair) *Pair { return p.validate(i, &zero) }

func (p pair_vec) Len() uint { return uint(len(p)) }
