// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=mctree -id level -d VecType=level_vec -d Type=level github.com/platinasystems/elib/vec.tmpl]

package mctree

import (
	"github.com/platinasystems/elib"
)

type level_vec []level

func (p *level_vec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]level, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *level_vec) validate(i uint, zero *level) *level {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]level, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *level_vec) Validate(i uint) *level                 { return p.validate(i, (*level)(nil)) }
func (p *level_vec) ValidateInit(i uint, zero level) *level { return p.validate(i, &zero) }

func (p level_vec) Len() uint { return uint(len(p)) }
