// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=loop -id looperIn -d VecType=looperInVec -d Type=LooperIn github.com/platinasystems/elib/vec.tmpl]

package loop

import (
	"github.com/platinasystems/elib"
)

type looperInVec []LooperIn

func (p *looperInVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]LooperIn, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *looperInVec) validate(i uint, zero *LooperIn) *LooperIn {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]LooperIn, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *looperInVec) Validate(i uint) *LooperIn                    { return p.validate(i, (*LooperIn)(nil)) }
func (p *looperInVec) ValidateInit(i uint, zero LooperIn) *LooperIn { return p.validate(i, &zero) }

func (p looperInVec) Len() uint { return uint(len(p)) }
