// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=loop -id errorThread -d VecType=errorThreadVec -d Type=*errorThread github.com/platinasystems/elib/vec.tmpl]

package loop

import (
	"github.com/platinasystems/elib"
)

type errorThreadVec []*errorThread

func (p *errorThreadVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*errorThread, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *errorThreadVec) Validate(i uint) **errorThread {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*errorThread, l, c)
		copy(q, *p)
		*p = q
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}

func (p errorThreadVec) Len() uint { return uint(len(p)) }
