// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=loop -id Vi -d VecType=viVec -d Type=Vi github.com/platinasystems/elib/vec.tmpl]

package loop

import (
	"github.com/platinasystems/elib"
)

type viVec []Vi

func (p *viVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Vi, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *viVec) validate(i uint, zero *Vi) *Vi {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]Vi, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *viVec) Validate(i uint) *Vi              { return p.validate(i, (*Vi)(nil)) }
func (p *viVec) ValidateInit(i uint, zero Vi) *Vi { return p.validate(i, &zero) }

func (p viVec) Len() uint { return uint(len(p)) }
