// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=loop -id nextNode -d VecType=nextNodeVec -d Type=nextNode github.com/platinasystems/elib/vec.tmpl]

package loop

import (
	"github.com/platinasystems/elib"
)

type nextNodeVec []nextNode

func (p *nextNodeVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]nextNode, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *nextNodeVec) validate(i uint, zero *nextNode) *nextNode {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]nextNode, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *nextNodeVec) Validate(i uint) *nextNode                    { return p.validate(i, (*nextNode)(nil)) }
func (p *nextNodeVec) ValidateInit(i uint, zero nextNode) *nextNode { return p.validate(i, &zero) }

func (p nextNodeVec) Len() uint { return uint(len(p)) }
