// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=loop -id Ref -d VecType=RefVec -d Type=Ref github.com/platinasystems/elib/vec.tmpl]

package loop

import (
	"github.com/platinasystems/elib"
)

type RefVec []Ref

func (p *RefVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Ref, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *RefVec) Validate(i uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Ref, l, c)
		copy(q, *p)
		*p = q
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
}

func (p RefVec) Len() uint { return uint(len(p)) }
