// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id t1hook -d Package=main -d DepsType=t1HookVec -d Type=t1Hook -d Data=hooks github.com/platinasystems/elib/dep/dep.tmpl]

package main

import (
	"github.com/platinasystems/elib/dep"
)

type t1HookVec struct {
	deps  dep.Deps
	hooks []t1Hook
}

func (t *t1HookVec) Len() int         { return t.deps.Len() }
func (t *t1HookVec) Get(i int) t1Hook { return t.hooks[t.deps.Index(i)] }
func (t *t1HookVec) Add(x t1Hook, ds ...*dep.Dep) {
	for i := range ds {
		t.deps.Add(ds[i])
	}
	t.hooks = append(t.hooks, x)
}
