// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=iomux -id file -d Data=files -d PoolType=filePool -d Type=Filer github.com/platinasystems/elib/pool.tmpl]

package iomux

import (
	"github.com/platinasystems/elib"
)

type filePool struct {
	elib.Pool
	files []Filer
}

func (p *filePool) GetIndex() (i uint) {
	l := uint(len(p.files))
	i = p.Pool.GetIndex(l)
	if i >= l {
		p.Validate(i)
	}
	return i
}

func (p *filePool) PutIndex(i uint) (ok bool) {
	return p.Pool.PutIndex(i)
}

func (p *filePool) IsFree(i uint) (ok bool) {
	return p.Pool.IsFree(i)
}

func (p *filePool) Resize(n uint) {
	c := elib.Index(cap(p.files))
	l := elib.Index(len(p.files) + int(n))
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Filer, l, c)
		copy(q, p.files)
		p.files = q
	}
	p.files = p.files[:l]
}

func (p *filePool) Validate(i uint) {
	c := elib.Index(cap(p.files))
	l := elib.Index(i) + 1
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Filer, l, c)
		copy(q, p.files)
		p.files = q
	}
	if l > elib.Index(len(p.files)) {
		p.files = p.files[:l]
	}
}

func (p *filePool) Elts() uint {
	return uint(len(p.files)) - p.FreeLen()
}
