// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elog -id GenEvent -d Type=GenEvent github.com/platinasystems/elib/elog/event.tmpl]

package elog

import (
	"fmt"
	"unsafe"
)

var GenEventType = &EventType{}

func init() {
	GenEventType.Stringer = func(e *Event) string {
		x := (*GenEvent)(unsafe.Pointer(&e.Data[0]))
		return x.String()
	}
}

func GenEventNew() (x *GenEvent) {
	e := Add(GenEventType)
	if unsafe.Sizeof(*x) > unsafe.Sizeof(e.Data) {
		panic(fmt.Sprintf("type too large: GenEvent %d bytes", unsafe.Sizeof(*x)))
	}
	x = (*GenEvent)(unsafe.Pointer(&e.Data[0]))
	return
}

func (x GenEvent) Log() {
	p := GenEventNew()
	*p = x
}

func (x *GenEvent) Event() (e *Event) {
	e = (*Event)(unsafe.Pointer(uintptr(unsafe.Pointer(x)) - unsafe.Offsetof(e.Data)))
	return
}

func (x *GenEvent) LogEventString(l *Log) string {
	e := x.Event()
	return fmt.Sprintf("%s: %s", e.EventString(l), x)
}

func (x *GenEvent) EventString() string { return x.LogEventString(DefaultLog) }
