// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elog -id GenEvent -d Type=GenEvent github.com/platinasystems/elib/elog/event.tmpl]

package elog

import (
	"fmt"
	"unsafe"
)

var GenEventType = &EventType{
	Name: "elog.GenEvent",
}

func init() {
	t := GenEventType
	t.Stringer = stringer_GenEvent
	t.Encoder = encoder_GenEvent
	t.Decoder = decoder_GenEvent
	RegisterType(GenEventType)
}

func stringer_GenEvent(e *Event) string {
	var x GenEvent
	b := (*[EventDataBytes]byte)(unsafe.Pointer(&x))
	copy(b[:], e.Data[:])
	return x.String()
}

func encoder_GenEvent(b []byte, e *Event) int {
	x := (interface{})((*GenEvent)(unsafe.Pointer(&e.Data[0])))
	if y, ok := x.(EventDataEncoder); ok {
		return y.Encode(b)
	} else {
		return copy(b, e.Data[:])
	}
}

func decoder_GenEvent(b []byte, e *Event) int {
	x := (interface{})((*GenEvent)(unsafe.Pointer(&e.Data[0])))
	if y, ok := x.(EventDataDecoder); ok {
		return y.Decode(b)
	} else {
		return copy(e.Data[:], b)
	}
}

func GenEventNew() (x *GenEvent) {
	e := Add(GenEventType)
	if unsafe.Sizeof(*x) > unsafe.Sizeof(e.Data) {
		panic(fmt.Sprintf("type too large: GenEvent %d bytes", unsafe.Sizeof(*x)))
	}
	x = (*GenEvent)(unsafe.Pointer(&e.Data[0]))
	return
}

func (x GenEvent) Log() {
	p := GenEventNew()
	*p = x
}

func (x *GenEvent) Event() (e *Event) {
	e = (*Event)(unsafe.Pointer(uintptr(unsafe.Pointer(x)) - unsafe.Offsetof(e.Data)))
	return
}

func (x *GenEvent) LogEventString(l *Log) string {
	e := x.Event()
	return fmt.Sprintf("%s: %s", e.EventString(l), x)
}

func (x *GenEvent) EventString() string { return x.LogEventString(DefaultLog) }
