// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elog -id Event -d VecType=EventVec -d Type=Event github.com/platinasystems/elib/vec.tmpl]

package elog

import (
	"github.com/platinasystems/elib"
)

type EventVec []Event

func (p *EventVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Event, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *EventVec) validate(i uint, zero *Event) *Event {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]Event, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *EventVec) Validate(i uint) *Event                 { return p.validate(i, (*Event)(nil)) }
func (p *EventVec) ValidateInit(i uint, zero Event) *Event { return p.validate(i, &zero) }

func (p EventVec) Len() uint { return uint(len(p)) }
